server.port=8080

# --- Configuración para tu base de datos local ---
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ligacut?allowPublicKeyRetrieval=true&useSSL=false
# AHORA USAMOS EL NUEVO USUARIO DEDICADO
spring.datasource.username=ligacut_user
spring.datasource.password=1234

# --- URL Ficticia para la API de equipos ---
api.equipos.url=http://localhost:8081/api